### ISSUE TITLE
Circular dependency bug while testing rack-app application

### ISSUE THREAD

**Issue by JoWilfrid** [rack-app/rack-app#22] opened 2017-04-04 12:54 UTC
Hello, it's me ♬ (again)

As I'm writing tests for all my `rack-app` APIs I'm facing a (non-blocking) bug caused by a circular dependency.
It looks like, in a test context, it creates a infinite loop between 2 inclusions: `rack/app` requires `rack/app/version` which requires `rack/app`.

The code in `lib/rack/app/version.rb` is as following:

```ruby
require 'rack/app'
Rack::App::VERSION = File.read(File.join(File.dirname(__FILE__), '..', '..', '..', 'VERSION')).strip
```

You can find a project that reproduced the bug [here](https://github.com/JoWilfrid/rack-app-tests-circular-dependency-bug)

It seems to occur around this line:

```ruby
RACK_APP = Rack::Builder.parse_file('config.ru').first
```

The test library used is `minitest` without rspec.

Hope there is enough details. Feel free to ask for any missing information.

PS: thank you again for this project ;)

**Comment by adamluzsi** [comment] 2017-04-07 02:34
Hello @JoWilfrid ! :))

I will look into the problem today and came up with a solution for this. 
Big thanks for reporting this !!! 👍 

Ps: you are awesome!  
Super detailed issue!

**Comment by adamluzsi** [comment] 2017-04-07 02:40
By the way out of curiosity, why do you need rack-test. ? 
Is it it related perhaps to some kind of fact that the built in test module (Rack::App::Test) not play along with minitest maybe ?

Cause than that's worth to me for an another in investigation :D

**Comment by adamluzsi** [comment] 2017-04-07 06:42
I fixed the Circular dependency bug and created a pull request for your bug example repo.
I had the courage to put a little example for the built in rack-app test module in the test file. :D 

Please check your main other projects, that the problem had been resolved everywhere with this! :)

**Comment by adamluzsi** [comment] 2017-04-08 05:52
@JoWilfrid could you ping me here, if the issue is resolved? : )

**Comment by adamluzsi** [comment] 2017-04-10 15:50
I close this issue, but if you still have any problem, don't hesitate to reopen, and I'm eager to help you out! : )

**Closed by adamluzsi** 2017-04-10 15:50 UTC

**Comment by JoWilfrid** [comment] 2017-04-18 14:16
Hi @adamluzsi !
Sorry for this late answer, I was very focused on something else.

Thank you very much for your fix & example & reactivity! :smile: 

See you soon (in another issue?) haha

**Comment by adamluzsi** [comment] 2017-04-18 14:29
Anytime for you!

But I hope it will be a feature request next time! :D
